CREATE TABLE IF NOT EXISTS  plans(
    idplan INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    planname TEXT NOT NULL CHECK ('typplan' <> ''),
    price DECIMAL NOT NULL,
    typplan TEXT NOT NULL CHECK ('typplan' <> '')
    );
CREATE TABLE IF NOT EXISTS  profits(
    idpro INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profitsname TEXT NOT NULL CHECK ('profits' <> '')
   );
CREATE TABLE IF NOT EXISTS  planpro(
    idplanpro INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idplan INTEGER REFERENCES profits(idpro),
    idpro INTEGER REFERENCES profits(idpro)
  );
CREATE TABLE IF NOT EXISTS  banner(
    idbanner INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    textheader TEXT NOT NULL CHECK ('textheader' <> ''),
    textbody TEXT NOT NULL CHECK ('textbody' <> ''),
    textfooter TEXT NOT NULL CHECK ('textfooter' <> ''),
    imgback TEXT NOT NULL CHECK ('imgback' <> '')
  );